# Generated by Django 4.2.1 on 2023-05-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Kurs adi giriniz', max_length=100, unique=True, verbose_name='Kurs Adi')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='courses/default_course.jpg', upload_to='courses/%Y/%m/%d/')),
                ('date', models.DateField(auto_now=True)),
                ('avaliable', models.BooleanField(default=True)),
            ],
        ),
    ]
